version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
steps:
  
  clone_init:
    title: Init Clone
    stage: "clone"
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="parser"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"

  main_clone:
    title: Clone Main Repo
    stage: "clone"
    type: "git-clone"
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"

  prepare:
    title: Prepare Dependencies
    stage: build
    image: 'kubevious/node-builder:14'
    working_directory: ${{main_clone}}
    commands:
      - npm ci
    
  compile:
    title: Compile
    stage: build
    image: 'kubevious/node-builder:14'
    working_directory: ${{main_clone}}
    commands:
      - npm run build
    